### ISSUE TITLE
Simplify and extend diagonal computation

### ISSUE THREAD

**Issue by DavidSCN** [DavidSCN/matrix-free-dealii-precice#25]
[Matrix-free](https://dealii.org/developer/doxygen/deal.II/tools_8h_source.html#l00259) tools enable a rather simple handling of the diagonal computation as opposed to the implementation here. Also, it would allow to use hanging nodes and adaptive meshes. However, the problem is that in the predefined functions, the [local_vmult](https://dealii.org/developer/doxygen/deal.II/namespaceMatrixFreeTools.html#a523190adf5671e317d745fed4b1d357f) interface is a bit too strict. We require explicit knowledge of the cell batch number in order to access the cached quantities which is not allowed by the current interface.
It would be very easy to add this additional parameter to the matrix-free tools (std::function parameter) since the information is already in the code. @peterrum any opinions?

**Comment by peterrum** [comment]
You can use `FEEvaluation::get_current_cell_index()` for that purpose.

**Comment by DavidSCN** [comment]
Ah perfect, I guess the interface is just growing too fast for me :smile:

**Comment by peterrum** [comment]
> Ah perfect, I guess the interface is just growing too fast for me smile

Keep me posted if something is missing or odd (or unusable). For me (and couple of others), the current interface works quite well.

**Comment by DavidSCN** [comment]
Will do that, thanks!
